"""
PURPOSE
-------
Define the validated public request and response contracts for the
French Property Intelligence API.

The prediction schemas describe the information required for property
valuation.

The location schemas provide a separate geocoding contract used by
contextual services such as the interactive map.

The environment schemas expose nearby contextual information without
changing the frozen machine-learning prediction contract.

The description schemas expose a separate GenAI presentation service.
Generative AI does not participate in property valuation.

Latitude and longitude remain generated by the official geocoding
service. They are never entered manually by the user.
"""

from typing import Literal

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------
# Location schemas
# ---------------------------------------------------------------------

class LocationRequest(BaseModel):
    """
    User-facing address that should be resolved by the geocoding service.

    PURPOSE:
    Give contextual features such as the map access to the property's
    resolved coordinates without changing the frozen /predict contract.
    """

    address: str = Field(
        ...,
        min_length=5,
        max_length=300,
        description="French postal address to geocode.",
    )

    @field_validator("address")
    @classmethod
    def clean_address(cls, value: str) -> str:
        """Remove unnecessary surrounding whitespace."""

        cleaned = value.strip()

        if not cleaned:
            raise ValueError("address cannot be empty.")

        return cleaned


class LocationResponse(BaseModel):
    """
    Public geographic information returned after address resolution.

    PURPOSE:
    Supply verified coordinates to map/context services while keeping
    geocoding centralized inside the FastAPI layer.
    """

    latitude: float
    longitude: float
    postcode: str
    resolved_address: str


# ---------------------------------------------------------------------
# Environment schemas
#
# PURPOSE:
# Return only cleaned public POI information to the client.
# Provider-specific Geoapify fields remain internal.
# ---------------------------------------------------------------------

class NearbyPlaceResponse(BaseModel):
    """One nearby point of interest."""

    name: str
    address: str
    distance_m: int
    latitude: float
    longitude: float


class EnvironmentResponse(BaseModel):
    """
    Nearby contextual information around one resolved property.

    The address is geocoded server-side before POIs are requested.
    """

    resolved_address: str
    postcode: str
    latitude: float
    longitude: float

    transport: list[NearbyPlaceResponse]
    green_spaces: list[NearbyPlaceResponse]
    supermarkets: list[NearbyPlaceResponse]


# ---------------------------------------------------------------------
# Prediction schemas
# ---------------------------------------------------------------------

class PredictionRequest(BaseModel):
    """User-facing information required to value one property."""

    property_type: Literal[
        "house",
        "maison",
        "apartment",
        "appartement",
    ]

    address: str = Field(
        ...,
        min_length=5,
        max_length=300,
        description="French postal address to geocode.",
    )

    surface_habitable: float = Field(
        ...,
        gt=0,
        le=1000,
        description="Habitable surface in square metres.",
    )

    n_pieces: int | None = Field(
        default=None,
        ge=1,
        le=50,
        description="Number of rooms. May be omitted.",
    )

    vefa: bool = Field(
        default=False,
        description="Whether the property is a VEFA transaction.",
    )

    @field_validator("address")
    @classmethod
    def clean_address(cls, value: str) -> str:
        """Remove unnecessary surrounding whitespace."""

        cleaned = value.strip()

        if not cleaned:
            raise ValueError("address cannot be empty.")

        return cleaned


class PredictionResponse(BaseModel):
    """Information returned after successful valuation."""

    estimated_price_eur: float
    property_type: str
    postcode: str
    resolved_address: str


# ---------------------------------------------------------------------
# GenAI description schemas
#
# PURPOSE:
# Give the language model only structured facts already obtained by the
# application. The LLM does not calculate or modify the valuation.
# ---------------------------------------------------------------------

class DescriptionPlace(BaseModel):
    """Minimal nearby-place information supplied to GenAI."""

    name: str
    distance_m: int | None = Field(
        default=None,
        ge=0,
    )


class DescriptionEnvironment(BaseModel):
    """Verified contextual information that may be described by GenAI."""

    transport: list[DescriptionPlace] = Field(
        default_factory=list
    )

    green_spaces: list[DescriptionPlace] = Field(
        default_factory=list
    )

    supermarkets: list[DescriptionPlace] = Field(
        default_factory=list
    )


class DescriptionRequest(BaseModel):
    """
    Verified property facts supplied to the description service.

    IMPORTANT:
    estimated_price_eur is an existing ML prediction. The GenAI service
    receives it only as text-generation context and never recalculates it.
    """

    property_type: Literal[
        "house",
        "maison",
        "apartment",
        "appartement",
    ]

    surface_habitable: float = Field(
        ...,
        gt=0,
        le=1000,
    )

    n_pieces: int | None = Field(
        default=None,
        ge=1,
        le=50,
    )

    vefa: bool = False

    resolved_address: str = Field(
        ...,
        min_length=3,
        max_length=300,
    )

    estimated_price_eur: float = Field(
        ...,
        gt=0,
    )

    environment: DescriptionEnvironment | None = None


class DescriptionResponse(BaseModel):
    """Generated natural-language presentation of verified facts."""

    description: str


# ---------------------------------------------------------------------
# Health schema
# ---------------------------------------------------------------------

class HealthResponse(BaseModel):
    """Minimal deployment health information."""

    status: str
    model_loaded: bool