"""
PURPOSE
-------
Define the validated public request and response contracts for the
French Property Intelligence API.

The prediction schemas describe the information required for property
valuation.

The location schemas provide a separate geocoding contract used by
contextual services such as the interactive map, nearby environment
and neighborhood exploration.

Latitude and longitude remain generated by the official geocoding
service. They are never entered manually by the user.
"""

from typing import Literal

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------
# Shared address validation
# ---------------------------------------------------------------------

class LocationRequest(BaseModel):
    """
    User-facing address that should be resolved by the geocoding service.

    PURPOSE:
    Give contextual features such as the map access to the property's
    resolved coordinates without changing the frozen /predict contract.
    """

    address: str = Field(
        ...,
        min_length=5,
        max_length=300,
        description="French postal address to geocode.",
    )

    @field_validator("address")
    @classmethod
    def clean_address(cls, value: str) -> str:
        """Remove unnecessary surrounding whitespace."""

        cleaned = value.strip()

        if not cleaned:
            raise ValueError("address cannot be empty.")

        return cleaned


class LocationResponse(BaseModel):
    """
    Public geographic information returned after address resolution.

    PURPOSE:
    Supply verified coordinates to map/context services while keeping
    geocoding centralized inside the FastAPI layer.
    """

    latitude: float
    longitude: float
    postcode: str
    resolved_address: str


# ---------------------------------------------------------------------
# Prediction schemas
# ---------------------------------------------------------------------

class PredictionRequest(BaseModel):
    """User-facing information required to value one property."""

    property_type: Literal[
        "house",
        "maison",
        "apartment",
        "appartement",
    ]

    address: str = Field(
        ...,
        min_length=5,
        max_length=300,
        description="French postal address to geocode.",
    )

    surface_habitable: float = Field(
        ...,
        gt=0,
        le=1000,
        description="Habitable surface in square metres.",
    )

    n_pieces: int | None = Field(
        default=None,
        ge=1,
        le=50,
        description="Number of rooms. May be omitted.",
    )

    vefa: bool = Field(
        default=False,
        description="Whether the property is a VEFA transaction.",
    )

    @field_validator("address")
    @classmethod
    def clean_address(cls, value: str) -> str:
        """Remove unnecessary surrounding whitespace."""

        cleaned = value.strip()

        if not cleaned:
            raise ValueError("address cannot be empty.")

        return cleaned


class PredictionResponse(BaseModel):
    """Information returned after successful valuation."""

    estimated_price_eur: float
    property_type: str
    postcode: str
    resolved_address: str


# ---------------------------------------------------------------------
# Health schema
# ---------------------------------------------------------------------

class HealthResponse(BaseModel):
    """Minimal deployment health information."""

    status: str
    model_loaded: bool